define(['jquery-ui',
        'jquery.xml2json',
        'jquery.ba-bbq',
        'jquery.timer',
        'jquery.ui.touch-punch',
        'jquery.validate',
        'jquery.tristate',
        'jquery.multiselect',
        'jquery.multiselect.filter',
        'jquery.steps.min',
        'jquery.panzoom',
        'jquery.ui.position',
        'jquery-contextmenu',
        'jquery.event.drag',
        'jquery.json',
        'jquery.droppick',
        'jquery.datetimepicker'
], function() {});
